application:
  name: twitter-clone-boot
  project: Twitter-Clone
  publicly_accessible: true
databases:
  - type: postgresql
    version: "11.5"
    name: my-postgresql-8628210
routers:
  - name: main
    routes:
      - application_name: twitter-clone-boot
        paths:
          - /