spring:
  jpa:
    show-sql: true
server:
  port: 9090
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true

---
spring:
  profiles: prod
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    url: "jdbc:${QOVERY_DATABASE_MY_POSTGRESQL_7274989_CONNECTION_URI_WITHOUT_CREDENTIALS}"
    username: ${QOVERY_DATABASE_MY_POSTGRESQL_274989_USERNAME}
    password: ${QOVERY_DATABASE_MY_POSTGRESQL_274989_PASSWORD}
